# Generated by Django 3.1.7 on 2021-05-24 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='parent',
        ),
    ]
